name: Cross-compile with fyne-cross

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Install fyne-cross
      run: go install github.com/fyne-io/fyne-cross@latest
    - name: Cross-compile for Windows
      run: fyne-cross windows -app-id com.cloonar.soundscapesync ./cmd/soundscape-sync/main.go
    - name: Cross-compile for Linux
      run: fyne-cross linux ./cmd/soundscape-sync/main.go
    - name: Cross-compile for macOS
      run: fyne-cross darwin ./cmd/soundscape-sync/main.go
