name: Cross-compile with fyne-cross

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Install fyne-cross
      run: go install github.com/fyne-io/fyne-cross@latest
    - name: Cross-compile for Windows
      run: fyne-cross windows
    - name: Cross-compile for Linux
      run: fyne-cross linux
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v3
      with:
        name: windows-build
        path: fyne-cross/bin/windows-amd64
        
    - name: Upload Linux artifact
      uses: actions/upload-artifact@v3
      with:
        name: linux-build
        path: fyne-cross/bin/linux-amd64
  build-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Install fyne-cross
      run: go install github.com/fyne-io/fyne-cross@latest
    # - name: Install Homebrew
    #   run: |
    #     /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    # - name: Install Docker
    #   run: |
    #     brew install docker
    - name: Set up Docker
      uses: crazy-max/ghaction-setup-docker@v3
    - name: Build Fyne application for macOS
      env:
        CGO_ENABLED: 1
        GOOS: darwin
        GOARCH: amd64 # Change if targeting a different architecture
        CC: o32-clang # Specify your C compiler here
      run: |
        set -x
        docker version
        fyne-cross darwin
    - name: Upload macOS artifact
      uses: actions/upload-artifact@v3
      with:
        name: macos-build
        path: fyne-cross/bin/darwin-amd64
